import Head from 'next/head'
import Login from '../components/Login'
import { useAuth } from '../context/AuthContext'
import UserDashboard from '@/components/UserDashboard'

export default function Home() {
  const { currentUser } = useAuth()

  return (
    < >
      <Head>
        <title>Lakuin Sekarang!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <UserDashboard/>}
    </>
  )
}
